apiVersion: v1
kind: Service
metadata:
  name: vchevill-playground
  labels:
    app: will
spec:
  type: LoadBalancer
  selector:
      app: will
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888