apiVersion: apps/v1
kind: Deployment
metadata:
  name: vchevill-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vchevill-playground
  template:
    metadata:
      labels:
        app: vchevill-playground
    spec:
      containers:
      - name: wil-playground
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: vchevill-playground
spec:
  selector:
    app: vchevill-playground
  ports:
  - name: http
    port: 8888
    targetPort: 8888
  type: LoadBalancer